# Generated by Django 5.1.4 on 2025-02-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangxahois', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baidang',
            name='hinh_anh',
        ),
    ]
