# Generated by Django 5.1.4 on 2025-02-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangxahois', '0002_remove_baidang_hinh_anh'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manually_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
