# Generated by Django 5.1.4 on 2025-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangxahois', '0003_user_manually_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/cover_images/%Y/%m/'),
        ),
    ]
